spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event
    username: postgres
    password: 14271915
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: true




